version: '3'
services:
  react-app:
    container_name: react-app
    build:
      context: ./react-app
    volumes:
      - './react-app:/usr/src/app'
      - '/react-app/usr/src/app/node_modules'
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: ./rails-app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-app/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
